# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-03 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_music_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duanzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duanzi_context', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Liuyanban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyTime', models.DateTimeField(auto_now_add=True)),
                ('lyb_context', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tupian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='斗图', max_length=100)),
                ('imgsrc', models.CharField(max_length=255)),
            ],
        ),
    ]
